version: "3.9"

services:
  # Frontend (React + Vite + Nginx Production)
  frontend:
    build: .
    container_name: sigec-frontend
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sigec-web.rule=Host(`sigec.artbenshow.com`)"
      - "traefik.http.routers.sigec-web.entrypoints=websecure"
      - "traefik.http.routers.sigec-web.tls.certresolver=letsencrypt"
      - "traefik.http.services.sigec-web.loadbalancer.server.port=80"
      - "traefik.docker.network=web"

networks:
  web:
    external: true
